### ISSUE TITLE
Abbreviated long option

### ISSUE THREAD

**Issue by ashayshirwadkar** [javier-lopez/genpass#13]
I am not sure if abbreviated long option is intended or not. But it seems to be an issue.
Should it be exact match?

For example, command `./genpass --nam foo --passw bar` passes

**Comment by javier-lopez** [comment]
I don't see such behavior as an issue, unless it collapse in some scenarios, however in such cases I'd add code to help the user define more clearly what it desires, but in general I prefer it as it's now.

**Comment by ashayshirwadkar** [comment]
okay.. Cool :+1:
