### ISSUE TITLE
genpass is looking for libscrypt.so.0 in the wrong place

### ISSUE THREAD

**Issue by duck2** [javier-lopez/genpass#17]
On debian testing, doing the straightforward compile

```
git clone https://github.com/chilicuil/genpass
make
./genpass
```

will result in `./genpass: error while loading shared libraries: libscrypt.so.0: cannot open shared object file: No such file or directory
`. 

However, running genpass from within libscrypt/ folder as in

```
cd libscrypt/
../genpass
```

will normally work which suggests there is an issue with gcc -L parameter or something.

**Comment by javier-lopez** [comment]
Hello @libduck2 , by default genpass will look for its shared libraries in either the local directory **'.'** or a system wide one, eg. **/usr/lib/** , on Debian|Ubuntu the system wide scrypt library can be installed with the **libscrypt0** package.

```
$ readelf -d ./genpass | grep RPATH 2>/dev/null
 0x000000000000000f (RPATH)              Library rpath: [.]
$  ldd genpass
        linux-vdso.so.1 =>  (0x00007ffd991cd000)
        libscrypt.so.0 => /usr/lib/libscrypt.so.0 (0x00007ffa17943000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffa17573000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563396c03000)
```

The above behavior IMO is the correct one, users will need to decide explicitly if they use the system wide libraries or the local ones. They can always use the ./genpass-static binary if they prefer to get started as fast as possible.

Still, if you prefer to add the libscrypt/ directory to the default RPATH variable, you could do it by modifying the main [Makefile](https://github.com/chilicuil/genpass/blob/master/Makefile#L10) on line 10 to:

`CFLAGS_EXTRA?=-Wl,-rpath=.,-rpath=./libscrypt/`

```
$ readelf -d ./genpass | grep RPATH 2>/dev/null
 0x000000000000000f (RPATH)              Library rpath: [.:./libscrypt/]
$ ldd genpass
        linux-vdso.so.1 =>  (0x00007ffc11605000)
        libscrypt.so.0 => ./libscrypt/libscrypt.so.0 (0x00007f541fe13000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f541fa2b000)
        /lib64/ld-linux-x86-64.so.2 (0x000056282482a000)
```

**Comment by duck2** [comment]
If `libscrypt-dev` or `libscrypt0` is not documented as a dependency and we are bundling `libscrypt`, I think the default setting should be using the libscrypt bundled and built with it. At least, if the default behaviour is not finding the library, it should be documented- "install libscrypt0 or add this path to your LD_LIBRARY_PATH or set rpath before compiling"

Another option is dropping the dependency and the dynamic linking and simply statically linking the final binary, however glibc is too big to statically link against by default and pulling in musl-libc looks freak-ish. This also creates the burden of updating the bundled `libscrypt` regularly.

**Comment by javier-lopez** [comment]
I've documented the `libscrypt` dependency into the [README.md](https://github.com/chilicuil/genpass/commit/25934b3d253796405e5a00c83eb9c40e1cc96993) file, hopefully it will help to avoid future confusions =), I'll keep both, dynamic and static linking, I prefer the user to decide which one to use, and indeed using a local libscrypt copy could be a burden but I think it makes the project self-contained and I like it that way. In the future if dependencies become a real problem I'll explore alternatives to manage them. Thank you for your detailed comments!

**Comment by duck2** [comment]
I think documenting the dependency removes the confusion here. Thanks for addressing the issue.
