### ISSUE TITLE
The name (-n) option is ignored

### ISSUE THREAD

**Issue by javier-lopez** [javier-lopez/genpass#2]
The name (-n) option is ignored. Generated password is the same no matter what you put in for name, even if left blank.

**Comment by mchoube** [comment]
I would like take this up.

**Comment by javier-lopez** [comment]
Thank you both @mchoube , @ashayshirwadkar this issue is now fixed :tada: in https://github.com/chilicuil/genpass/commit/bad1b93ac309f2e9b148dfda7f451df661e9e032
